#!/bin/sh

ENABLED=yes

DESC="Netbird Client"
PROCS="netbird"
PROG="/opt/sbin/$PROCS"

{ [ -f "/opt/etc/$PROCS/env" ] && . /opt/etc/"$PROCS"/env ; } || \
{ printf "\033[1;31m %s \033[0m\n" "Abort: conf file not found." && exit 1 ; }

start_pre() {
#  rm -f /opt/var/run/"$PROCS".sock
  for i in /opt/var/lib/"$PROCS" /opt/var/log/"$PROCS"; do
    [ -d "$i" ] || {
      mkdir -pm 0755 "$i"
    }
  done
}

PRECMD="start_pre"
ARGS="service run $FLAGS"
PREARGS=""

. /opt/etc/init.d/rc.func
