#!/bin/sh

ENABLED=yes

DESC="AdGuard Home"
PROCS="AdGuardHome"
PROG="/opt/bin/$PROCS"

{ [ -f "/opt/etc/$PROCS/adguardhome.conf" ] && \
. /opt/etc/$PROCS/adguardhome.conf ; } || \
{ printf "\033[1;31m %s \033[0m\n" "Abort: conf file not found." && exit 1 ; }

PID_FILE="/opt/var/run/$PROCS.pid"

ARGS="$OPTIONS"
PREARGS=""

. /opt/etc/init.d/rc.func
